#!/usr/bin/env bash

TOP=$(top -bn1 -o %CPU  U i  -w 200| sed -n '/USER/{n;p;}' )

PID=$( echo ${TOP} | awk '{ printf("%s", ""$1""); }')
CPU=$( echo ${TOP} | awk '{ printf("%s",""$9""); }' | cut -f1 -d".")
PROC=$(echo ${TOP} | awk '{ printf("%s",""$12""); }')

if [ "$1" == "kill" ]; then
  bkill=$(zenity --question --text "Kill this shit?\n$PROC\nPID: $PID"; echo $?)
  if [ $bkill -eq 0 ]; then
  	kill -9 $PID
  fi
fi

out=$(echo $CPU $PROC)

declare -r urgent=#00FF00
declare -r normal=#555

if [[ $CPU -ge 50 ]]; then
    out=$(echo "%{F$urgent} $out %{F-}")
else
    out=$(echo "%{F$normal} $out %{F-}")
fi

echo "$out"
