#!/usr/bin/env bash

declare -r SPOTIFY_REMOTE="/home/i/proj/my_spotify_cli/spotify_remote.sh"
declare -r SPOTIFY_WALL="/home/i/proj/my_spotify_cli/set_cover_wallpaper.sh"
declare -r WALL="/home/i/wall/wall.jpg"
declare -r CUR_WALL=`dirname $0`/cur_wall.ignore

# kde_set_wall
. ~/.my_zsh/user_func.sh

set_wall()
{
	local w="$1"
	local cur_wall=$(cat "$CUR_WALL" 2>/dev/null)

	[[ "$cur_wall" == "$w" ]] && return 0;

	if [ $w == $WALL ]; then
		# feh --bg-scale $w;
		kde_set_wall $w
	else
		$SPOTIFY_WALL "$WALL" "$w" 1
	fi
	echo $w > $CUR_WALL
}

[[ -n `playerctl -p spotify metadata artist 2>/dev/null` ]] && is_local=true || is_local=false;


# if [ $is_local = true ]; then
# 	out=$(playerctl -p spotify metadata --format "{{ artist }} - {{ title }}")
# 	set_wall $WALL
# else
	current=$($SPOTIFY_REMOTE -mi)

	if [ -z "$current" ]; then
		echo "%{F#13E56F}%{F-}"

		is_local=true
		set_wall $WALL
		exit
	fi

	current_song=$(echo $current | jq .name)
	current_song_album_image=$(echo $current | jq .image | tr -d '"')
	current_artists=$(echo $current | jq .artists )
	current_device=$(echo $current | jq .device.name)
	current_device_type=$(echo $current | jq .device.type)
	current_device_volume=$(echo $current | jq .device.volume)

	case $current_device_type in
		\"Computer\") current_device_type="";;
		\"Smartphone\") current_device_type="";;
		\"Speaker\") current_device_type="蓼";;
		\"CastAudio\") current_device_type="";;
	esac

	set_wall "$current_song_album_image"

	c_song="%{F#13E56F}"
	c_extra="%{F#2d7b4f}"
	c_close="%{F-}"

	out=$(echo "$c_song $current_artists - $current_song$c_close $c_extra[$current_device $current_device_type 奄$current_device_volume]$c_close" | tr -d '"')
# fi

echo $out
